### ISSUE TITLE
Multiple bulk-requires in a single file cause issues

### ISSUE THREAD

**Issue by cphoover** [substack/bulkify#5]
var bulk = require("bulk-require");
    
    var unattachedPartials = bulk(__dirname + "/../", ["pages/*.js"]   ) ; 
    var unattachedHelpers  = bulk(__dirname + "/../", ["helpers/*.js"] ) ; 
    
    console.log("unattachedHelpers"  , unattachedHelpers  ) ; 
    console.log("unattachedPartials" , unattachedPartials ) ; 

Will cause an "[X]/frontend/js/test-bulk.js" to be thrown or sometimes I get "Invalid left hand assignment"

But if I do 

    var bulk = require("bulk-require");
    var unattachedPartialsHelpers = bulk(__dirname + "/../", ["pages/*.js", "helpers/*.js"] ) ; 
    console.log("unattachedPartialsHelpers" , unattachedPartialsHelpers ) ; 

That works.. 

I'm using v 1.01. Haven't really traced down what is causing this issue yet. If I get some time I will try to later.  If one of these successfully build I would expect both of them to.

**Comment by vvo** [comment]
@JamesKyburz thanks, works great!

**Comment by substack** [comment]
Just fixed upstream in static-module. Upgrade to bulkify 1.1.1 to get the fix:

``` js
var bulk = require('bulk-require');

var pages = bulk(__dirname, [ 'pages/*.js' ]); 
var helpers  = bulk(__dirname, [ 'helpers/*.js' ]); 
console.log(pages);
console.log(helpers);
```

``` sh
 $ browserify -t bulkify test.js | node
{ pages: { a: 3, b: 4, c: 5 } }
{ helpers: { x: 300, y: 400 } }
```
